### ISSUE TITLE
Does not record failures with gauge 1.5.0

### ISSUE THREAD

**Issue by hazzik** [getgauge/xml-report#50]
### Expected behavior
Report from v1.4.3
```xml
<testsuites>
	<testsuite id="1" tests="1" failures="1" package="/var/tmp/specs/pipelineEnrolment/companyPipelineEnrolment.spec" time="62.398" timestamp="2023-06-23T13:56:24" name="Login" errors="0" hostname="09b60b91a660">
		<properties></properties>
		<testcase classname="Login" name="Login" time="62.398">
			<failure message="Login &lt;name&gt;&#xA;Concept Execution Failure: &#39;Failed to check onboarding via API&#39;" type="Login &lt;name&gt;&#xA;Concept Execution Failure: &#39;Failed to check onboarding via API&#39;">Error: Failed to check onboarding via API&#xA;    at onboardingCheck (/var/tmp/tests/stepImplementations/authentication.ts:65:11)&#xA;    at processTicksAndRejections (node:internal/process/task_queues:96:5)&#xA;    at AuthenticationImpl.authenticateSilently (/var/tmp/tests/stepImplementations/authentication.ts:83:30)</failure>
		</testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
</testsuites>
```

### Actual behavior
Report from v1.5.0
```xml
<testsuites>
	<testsuite id="1" tests="1" failures="1" package="/var/tmp/specs/pipelineEnrolment/companyPipelineEnrolment.spec" time="62.053" timestamp="2023-06-23T13:49:39" name="Login" errors="0" hostname="364647ae5b55">
		<properties></properties>
		<testcase classname="Login" name="Login" time="62.053"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
</testsuites>
```

### Steps to reproduce
1. Update gauge to 1.5.0

### Gauge version
```
Gauge version: 1.5.0
Commit Hash: 2946c75

Plugins
-------
html-report (4.2.0)
screenshot (0.1.0)
ts (0.1.0)
xml-report (0.3.1)
```

**Comment by haroon-sheikh** [comment]
@hazzik I've pushed a new release of xml-report v0.4.0 to fix the issue. 

Let me know if that fixes for you.
